### PR TITLE
Breaking/tao 4814 atomic bundles

### PR DESCRIPTION
**Pull request by krampstudio**
Migrate the extension to atomic bundles

Requires : 
 - [x] https://github.com/oat-sa/tao-core/pull/1842

### CODE REVIEW

**Review by oatymart — CHANGES_REQUESTED** [review]
Couple of problems:
- taoProctoring dependency should be version 11.0.0 according to spreadsheet, but 9.0.0 listed
- after merging, the `npx grunt taotestcenterbundle` task failed with the following error:
```
ENOENT: no such file or directory, open '/Users/martinnicholson/work/htdocs/tao14/tao/views/build/output/taoProctoring/helper/textConverter.js'
In module tree:
    taoTestCenter/controller/ProctorManager/index
      taoTestCenter/component/proctorForm
```

**Comment by krampstudio** [comment]
Fixed

**Comment by krampstudio** [comment]
@oatymart please check again and update your review accordingly

**Comment by oatymart** [comment]
With the latest version on this branch, my `npx grunt taotestcenterbundle` task still fails.
```
>> Error: Error: ENOENT: no such file or directory, open '/Users/martinnicholson/work/htdocs/tao15/tao/views/build/output/taoProctoring/helper/textConverter.js'
>> In module tree:
>>     taoTestCenter/controller/ProctorManager/index
>>       taoTestCenter/component/proctorForm
>>
>>     at Object.fs.openSync (fs.js:646:18)
Fatal error: Unable to bundle your code
```

Maybe @handleman you could also test this one if you have time?

**Comment by krampstudio** [comment]
please update the extension `taoProctoring`. Since they are dependent they need to be up to date for the bundler to create the dependency tree

**Review by oatymart — APPROVED** [review]
Got it. Versions and bundles all approved this time.

**Comment by jsconan** [comment]
All good! 👍

**Pull request merged**
